<table><tr><td> <em>Assignment: </em> Sample Flask App and Readings</td></tr>
<tr><td> <em>Student: </em> Samuel Raj Gandla (sg2434)</td></tr>
<tr><td> <em>Generated: </em> 11/3/2022 3:53:40 PM</td></tr>
<tr><td> <em>Grading Link: </em> <a rel="noreferrer noopener" href="https://learn.ethereallab.app/homework/IS601-005-F22/sample-flask-app-and-readings/grade/sg2434" target="_blank">Grading</a></td></tr></table>
<table><tr><td> <em>Instructions: </em> <ol><li>&nbsp;Follow the slides from class.&nbsp;</li><li>&nbsp;Get the sample app deployed to Heroku dev</li><li>&nbsp;Once finished with the slides create a pull request from the lesson branch to dev (don't close it yet)&nbsp;</li><li>&nbsp;Create an m6_submission.md file in the same directory as the flask sample app&nbsp;</li><li>&nbsp;Fill in the deliverables below&nbsp;</li><li>&nbsp;Generate the markdown and paste the content into the new md file&nbsp;</li><li>&nbsp;git add/commit/push&nbsp;</li><li>&nbsp;Complete the pull request&nbsp;</li><li>&nbsp;Create a pull request from dev to prod&nbsp;</li><li>&nbsp;Complete the merge&nbsp;</li><li>&nbsp;Locally checkout dev&nbsp;</li><li>&nbsp;git pull the latest dev changes&nbsp;</li><li>&nbsp;On GitHub navigate to the location of the m6_submission.md file from the prod branch&nbsp;</li><li>&nbsp;Grab that direct link and submit it to Canvas</li></ol></td></tr></table>
<table><tr><td> <em>Deliverable 1: </em> Proof App has been deployed </td></tr><tr><td><em>Status: </em> <img width="100" height="20" src="http://via.placeholder.com/400x120/009955/fff?text=Complete"></td></tr>
<tr><td><table><tr><td> <em>Sub-Task 1: </em> Screenshot the output of the app (including the url) showing it's running from Heroku dev</td></tr>
<tr><td><table><tr><td><img width="768px" src="https://user-images.githubusercontent.com/113142876/199816328-3530c32f-76c0-4594-b313-40c70b4ad40b.png"/></td></tr>
<tr><td> <em>Caption:</em> <p>The above url has the screenshot of required information as it was deployed<br>successfully . <br></p>
</td></tr>
</table></td></tr>
<tr><td> <em>Sub-Task 2: </em> Add a direct link to the app here (prod url)</td></tr>
<tr><td> <a rel="noreferrer noopener" target="_blank" href="https://is601-sg2434-prod.herokuapp.com/">https://is601-sg2434-prod.herokuapp.com/</a> </td></tr>
</table></td></tr>
<table><tr><td> <em>Deliverable 2: </em> Misc </td></tr><tr><td><em>Status: </em> <img width="100" height="20" src="http://via.placeholder.com/400x120/009955/fff?text=Complete"></td></tr>
<tr><td><table><tr><td> <em>Sub-Task 1: </em> Add a link to the pull request from Flask-Sample-HW to Dev</td></tr>
<tr><td> <a rel="noreferrer noopener" target="_blank" href="https://github.com/samuelrajgandla/IS601-PC37/pull/8">https://github.com/samuelrajgandla/IS601-PC37/pull/8</a> </td></tr>
<tr><td> <em>Sub-Task 2: </em> Did you have any issues during setup and if so how did you resolve them, otherwise what did you learn?</td></tr>
<tr><td> <em>Response:</em> <p>I had an issue with the installation, but now everything is fine.<br></p><br></td></tr>
</table></td></tr>
<table><tr><td> <em>Deliverable 3: </em> Readings </td></tr><tr><td><em>Status: </em> <img width="100" height="20" src="http://via.placeholder.com/400x120/009955/fff?text=Complete"></td></tr>
<tr><td><table><tr><td> <em>Sub-Task 1: </em> What can you tell me about docker? Describe the various steps needed to get an app ran inside a docker container in your own words</td></tr>
<tr><td> <em>Response:</em> <p>Docker file contains few command lines which runs the files, these are some<br>of the lines that used for this assignment :<div>1. This one is to<br>install&nbsp;<span style="font-family: &quot;Helvetica Neue&quot;; font-size: 13px;">Python Requirements.</span><div><div style="color: rgb(212, 212, 212); background-color: rgb(30,<br>30, 30); font-family: Menlo, Monaco, &quot;Courier New&quot;, monospace; font-size: 12px; line-height: 18px; white-space:<br>pre;"><span style="color: #c586c0;">RUN</span> <span style="color: #9cdcfe;">pip</span> <span style="color: #9cdcfe;">install</span> <span style="color: #9cdcfe;">-r</span> &lt;span<br>style=&quot;color: #9cdcfe;&quot;&gt;requirements.txt</span></div><div>2.This line is to run the&nbsp;<span style="font-family: &quot;Helvetica Neue&quot;; font-size: 13px;">service on<br>container startup and the next to lines are to copy code.</span></div></div></div><div><div style="color: rgb(212,<br>212, 212); background-color: rgb(30, 30, 30); font-family: Menlo, Monaco, &quot;Courier New&quot;, monospace; font-size:<br>12px; line-height: 18px; white-space: pre;"><span style="color: #c586c0;">CMD</span> <span style="color: #9cdcfe;">exec</span> <span style="color: #9cdcfe;">gunicorn</span><br><span style="color: #9cdcfe;">--bind</span> <span style="color: #9cdcfe;">:</span><span style="color: #9cdcfe;">$PORT</span> <span style="color: #9cdcfe;">--workers</span> <span style="color:<br>#9cdcfe;">1</span> <span style="color: #9cdcfe;">--threads</span> <span style="color: #9cdcfe;">8</span> <span style="color: #9cdcfe;">--timeout</span> <span style="color: #9cdcfe;">0</span><br><span style="color: #9cdcfe;">main:app</span></div><div style="color: rgb(212, 212, 212); background-color: rgb(30, 30, 30); font-family: Menlo,<br>Monaco, &quot;Courier New&quot;, monospace; font-size: 12px; line-height: 18px; white-space: pre;"><span style="color: rgb(197, 134,<br>192);">COPY</span> <span style="color: rgb(156, 220, 254);">.</span> <span style="color: rgb(156, 220, 254);">/src</span></div><div style="color: rgb(212,<br>212, 212); background-color: rgb(30, 30, 30); font-family: Menlo, Monaco, &quot;Courier New&quot;, monospace; font-size:<br>12px; line-height: 18px; white-space: pre;"><div><span style="color: #c586c0;">WORKDIR</span> <span style="color: #9cdcfe;">/src</span></div></div></div><br></p><br></td></tr>
<tr><td> <em>Sub-Task 2: </em> What is Heroku? Why do you feel it was chosen for this class?</td></tr>
<tr><td> <em>Response:</em> <p>Heroku is platform, which deploy the code and gives the output. Even though<br>there are few steps to follow and complete the setup in github to<br>deploy. But as much as I think Heroku is the right choice for<br>the class due to the level of work, which is easy and able<br>to study things.<div>And this is the short description of Heroku:</div><div>Heroku is a cloud<br>Platform as a Service that uses containers. Modern apps are deployed, managed, and<br>scaled by developers using Heroku. This platform provides developers with the quickest route<br>to releasing their apps onto the market since it is stylish, adaptable, and<br>simple to use.<br><div><br></div></div><br></p><br></td></tr>
<tr><td> <em>Sub-Task 3: </em> What is flask? List a few things you learned about it</td></tr>
<tr><td> <em>Response:</em> <p>Python is used to create the Flask web application framework. It was created<br>by Armin Ronacher, who served as the team leader of Poocco, an international<br>group of Python aficionados. The Werkzeg WSGI toolkit and the Jinja2 template engine<br>serve as the foundation for Flask. They&#39;re both Pocco projects.<br></p><br></td></tr>
<tr><td> <em>Sub-Task 4: </em> What is the difference between a Dockerfile and a Github Action .yml file?</td></tr>
<tr><td> <em>Response:</em> <p>The Dockerfile outlines how to create Docker images, whereas Docker-compose is used to<br>run Docker containers. This is the main distinction between the two.<br></p><br></td></tr>
</table></td></tr>
<table><tr><td><em>Grading Link: </em><a rel="noreferrer noopener" href="https://learn.ethereallab.app/homework/IS601-005-F22/sample-flask-app-and-readings/grade/sg2434" target="_blank">Grading</a></td></tr></table>